# Generated by Django 4.0.4 on 2022-05-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.CharField(default='no address', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='new', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='no item type', max_length=100),
        ),
    ]
