# Generated by Django 4.0.4 on 2022-05-08 03:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0013_product_address_product_status_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flags',
            field=models.ManyToManyField(related_name='flag_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
