# Generated by Django 4.0.4 on 2022-05-09 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0015_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1⭐ - VERY BAD'), (2, '2⭐ - BAD'), (3, '3⭐ - AVERAGE'), (4, '4⭐ - GOOD'), (5, '5⭐ - VERY GOOD')], default=5),
        ),
    ]
