# Generated by Django 4.0.4 on 2022-05-08 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ratings',
        ),
    ]
