# Generated by Django 4.0.4 on 2022-05-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_comment_name_alter_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
